version: "3"
services:
  redis:
    image: redis:5.0.3-alpine3.8
    restart: always
    volumes:
    - redis-data-istio:/var/lib/redis
    ports:
    - "6379:6379"
  mysql:
    image: 'mysql/mysql-server:5.7'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: useless
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
    - mysql-data-istio:/var/lib/mysql
    - ./config/mysql/my.cnf:/etc/my.cnf
    - ./config/mysql/:/docker-entrypoint-initdb.d/
    ports:
    - '3307:3306'
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
    - '9092:9092'
    depends_on:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.103
      KAFKA_CREATE_TOPICS: "test:1:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  jaeger:
    image: jaegertracing/all-in-one:1.7
    restart: always
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"
  influxdb:
    image: influxdb:1.5-alpine
    #    command:
    #      - /init-influxdb.sh
    environment:
      INFLUXDB_DB: test01
    #      INFLUXDB_ADMIN_ENABLED: !!bool true
    #      INFLUXDB_ADMIN_USER: test
    #      INFLUXDB_USER_PASSWORD: test
    #    volumes:
    #    - influxdb-local:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    ports:
      - "3000:3000"

volumes:
  mysql-data-istio:
  redis-data-istio: